# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/StankinsV2.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet install aop'
  inputs:
    command: custom

    custom: tool

    arguments: 'install -g dotnet-aop'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet run aop'
  inputs:
    command: custom

    custom: aop

    #arguments: '$(Build.Repository.LocalPath)\AOPRoslyn\processme.txt'

    workingDirectory: stankinsv2
    
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
