version: "3"
services:
    angular:
        build:
            context: .
            dockerfile: dockerAliveAngular            
        command: 
            - /bin/sh
            - -c
            - |
                npm i
                ng serve --host 0.0.0.0 --proxy-config proxy.conf.js --poll 500                

        volumes:
             - "./StankinsAliveAngular:/usr/app/"
             
        ports:
            - "4200:4200"
            - "49153:49153"
            
    netcore:
        build:
            context: .
            dockerfile: dockerNETCore   
            
        command: dotnet watch -p StankinsStatusWeb/StankinsAliveMonitor.csproj run --urls http://0.0.0.0:5000
            
        volumes:
             - "./:/usr/app/"
             
        ports:
            - "5000:5000"
            
    #netcoretest:
    #    build:
    #        context: .
    #        dockerfile: dockerNETCore   
    #    
    #    command: dotnet watch -p StankinsTestXUnit/StankinsTestXUnit.csproj test --filter ExternalDependency=0
    #        
    #    volumes:
    #         - "./:/usr/app/"
             