version: '3.7'
services:

  db:
   
    build: 
      context: .
      dockerfile: sqlserver.docker
    #image: mcr.microsoft.com/mssql/server 
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "<YourStrong!Passw0rd>"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S (local) -U SA -P '<YourStrong!Passw0rd>' -Q 'select 1'
      
      
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      
    environment:
      JENKINS_OPTS: "--argumentsRealm.passwd.admin=andrei --argumentsRealm.roles.user=admin --argumentsRealm.roles.admin=admin"
      JAVA_OPTS: "-Xmx4096m -Djenkins.install.runSetupWizard=false"
      
  cachet:
    image: ignatandrei/ci_cachet 
    ports:
      - "8000:8000"
      
    environment:
      APP_KEY: "base64:ybug5it9Koxwhfi5a6CORbWdpjVqXxkz/Tyj4K45GKc="
      DEBUG: "false" 
      DB_DRIVER: "sqlite"
       
    user: "1001"    
    working_dir: "/var/www/html" 
    entrypoint: "/sbin/entrypoint.sh"

